
workflows:

  android-deploy-workflow:
    name: Android Deployment WorkFlow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
    scripts: 
      - name: Set Android SDK location
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties" 
      - name: Build AAB
        script:  |
          cd $CM_BUILD_DIR
          flutter pub get
          flutter build appbundle
    artifacts:    
          - build/**/outputs/**/*.apk
          - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - romoloferreira@icloud.com
        notify:
          success: true
          failure: false      
  
          
                       

